### ISSUE TITLE
Test transfer land and approve land 

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#100]
Test transfer and approve land function. Ensure all edge cases are covered and it works. Update the logic to work if necessary.

**Comment by Iwueseiter** [comment]
I'd like to handle this task.

**Comment by manoahLinks** [comment]
I’d like to work on this.

My background
i'm a smart contract developer proficient in cairo

How i will tackle this
i will test for all cases based on the flow for both functions

i will ensure all assertions are met and test for failures incase of reverts
