### ISSUE TITLE
feat: create a land market store where people will be able to buy and sell lands

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#128]
Develop a marketplace for land listings:

- Allow owners to list lands with prices
- Search and filter functionality
- Land details page with images and documents
- Bidding system
- Price history tracking

**Comment by lauchaves** [comment]
Hey @fishonamos 👋  I'm Lau Chaves, and I came across this project—it caught my attention! I'd love to contribute and was wondering if I could work on this issue!
