### ISSUE TITLE
Add integration test to workflow

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#131]
We have an integration test that will soon be complete. We need to add it to the workflow.

**Comment by Mystic-Nayy** [comment]
@fishonamos  Please can i work on this?

**Comment by fishonamos** [comment]
> @fishonamos Please can i work on this? I'll add the integration test to the workflow by updating it?

Hi @Mystic-Nayy . This is an internal issue. However, you can apply to the feedback issue. We will open new issues.
