### ISSUE TITLE
Enhance  land registry smart contracts

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#137]
Currently, our land registry smart contract codes lacks appropriate comments. Comments are important because they help external contributors or reviewers understand the codebase.

**Comment by AYo101o** [comment]
@fishonamos please can I be assigned this issue? Will be sure to deliver a good job

**Comment by NueloSE** [comment]
@fishonamos can i work on this.

i have experience in writing smart contracts in cairo and solidity.

kindly assign me

**Comment by petersdt** [comment]
@fishonamos kindly assign me this as am good with technical writing 

previous contribution: [cairobook](https://github.com/cairo-book/cairo-book/pull/788)

**Comment by lauchaves** [comment]
Hi @fishonamos  👋  I’m Lau Chaves, and I saw the issue about adding comments to the land registry smart contract. I’m learning about smart contracts, and working on this would be a great chance to learn more while helping others understand the code better. I’d love to help out! lmk!

**Comment by jorgezerpa** [comment]
@fishonamos Hello! I can take a look on this👾
