### ISSUE TITLE
feat: add support for land registration

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#14]
as described above. 

Sample:

    struct Landreg {
       id;
        area;
       landAddress;
        landPrice;
        allLatitudeLongitude;
         allLongitude;
        propertyPID;
         physicalSurveyNumber;
         document;
        ownerAddress;
        isLandVerified;
    }

**Comment by GoSTEAN** [comment]
@fishonamos Assign this to me.

**Comment by GoSTEAN** [comment]
@fishonamos Give me another issue
