### ISSUE TITLE
test land market functions

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#151]
We have some functions in the market place that need to be tested. The functions are listed below:
```
    fn create_listing(ref self: TContractState, land_id: u256, price: u256) -> u256;
    fn cancel_listing(ref self: TContractState, listing_id: u256);
    
    
    fn update_listing_price(ref self: TContractState, listing_id: u256, new_price: u256);
    fn buy_land(ref self: TContractState, listing_id: u256);


    fn get_listing(self: @TContractState, listing_id: u256) -> Listing;
    fn get_active_listings(self: @TContractState) -> Array<u256>;

    fn get_listing_price_history(self: @TContractState, listing_id: u256) -> Array<(u256, u64)>;
  
  

 For each of them, pick two and test. This issue will be assigned to multiple contributors. Please comment with the one you want to work on.

**Comment by anonfedora** [comment]
Hi @fishonamos, I'm interested in testing
fn get_listing(self: @TContractState, listing_id: u256) -> Listing;
fn get_active_listings(self: @TContractState) -> Array<u256>;

**Comment by emarc99** [comment]
Hy, let me do below functions' test. Can handle cairo through completion of cairo NodeGurdians tests and starklings 2.0.


fn create_listing(ref self: TContractState, land_id: u256, price: u256) -> u256;
fn cancel_listing(ref self: TContractState, listing_id: u256);

**Comment by martinvibes** [comment]
hey @fishonamos can i work on this too

**Comment by dev-chinx** [comment]
hey @fishonamos let me take the last one 
fn get_listing_price_history(self: @TContractState, listing_id: u256) -> Array<(u256, u64)>;

**Comment by Akshola00** [comment]
hey @fishonamos can i join in on this

**Comment by fishonamos** [comment]
> hey @fishonamos can i work on this too i'm cool testing fn update_listing_price(ref self: TContractState, listing_id: u256, new_price: u256); fn buy_land(ref self: TContractState, listing_id: u256);

Take buy land

**Comment by Akshola00** [comment]
thanks 
on it now

> > hey @fishonamos can i join in on this
> 
> take update listing

**Comment by fishonamos** [comment]
> Hy, let me do below functions' test. Can handle Cairo through completion of Cairo NodeGurdians quests and Starklings 2.0.
> 
> fn create_listing(ref self: TContractState, land_id: u256, price: u256) -> u256; fn cancel_listing(ref self: TContractState, listing_id: u256);

Can you raise pr before end of day?

**Comment by Jagadeeshftw** [comment]
Give me one function @fishonamos

**Comment by fishonamos** [comment]
If no pr by end of day, we can assign to another person.

**Comment by SoarinSkySagar** [comment]
@fishonamos can I join this issue?

**Comment by emarc99** [comment]
> > Hy, let me do below functions' test. Can handle Cairo through completion of Cairo NodeGurdians quests and Starklings 2.0.
> > fn create_listing(ref self: TContractState, land_id: u256, price: u256) -> u256; fn cancel_listing(ref self: TContractState, listing_id: u256);
> 
> Can you raise pr before end of day?


Yes. On it now

**Comment by emarc99** [comment]
Almost done, I will pr in minutes.

**Comment by fishonamos** [comment]
We will close and reopen for odhack

**Comment by GideonBature** [comment]
Can you please assign me to test for these two?

    fn update_listing_price(ref self: TContractState, listing_id: u256, new_price: u256);
    fn buy_land(ref self: TContractState, listing_id: u256);
    
    Thank you!
