### ISSUE TITLE
test land market functions: create and cancel listing

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#165]
fn create_listing(ref self: TContractState, land_id: u256, price: u256) -> u256;
    fn cancel_listing(ref self: TContractState, listing_id: u256);

**Comment by NueloSE** [comment]
@fishonamos kindly assign me this task as i have experience writing and testing smart contracts in cairo. ETA <= 48hrs

**Comment by CollinsC1O** [comment]
I'm a front-end and a blockchain developer may I handle this issue?

**Comment by Akshola00** [comment]
Could I take on this issue?

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of other projects. can I work on this?

**Comment by Birdmannn** [comment]
Let me handle this one chief. I've been in your group chat since the last ODHack and I wasn't assigned any. Let me quickly hop on this and deliver you from such unnecessary bugs. I'm very grateful sir, my practice shall show workings

**Comment by No-bodyq** [comment]
I'd like to handle this task.

**Comment by SoarinSkySagar** [comment]
I would like to create the test functions. and i will make sure that the tests are valid and passing with edge cases too, please assign me @fishonamos

**Comment by casweeney** [comment]
## About me
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

## Tackling this Issue
I have looked at `create_listing()` and `cancel_listing()` functions, I will write tests for both functions.

For `create_listing()`, I will first create a listing and then use the `get_listing()` function to get the listing I created, then I will assert that the listen id passed returned the required properties, I will also assert for the emitted event.

For `cancel_listing()` I will create a listing, I will cancel the same listing I created, then assert that the cancelled listing was removed from active listing.

## ETA: 6-8 hours

**Comment by ShantelPeters** [comment]
I'd be happy to do this.

**Comment by emarc99** [comment]
I'd love to give this a go. Is this still available?

**Comment by Amarjeet325** [comment]
Let me try this one!

**Comment by ryzen-xp** [comment]
Could I take over this issue?

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by saimeunt** [comment]
Hey I'm a returning contributor to landver, would love to tackle this one as I've had multiple experiences in the past in testing Cairo contracts.

**Comment by suhas-sensei** [comment]
gm gm, Suhas here, having worked in the last od, where  I’ve worked on integrating on-chain mechanics into games and have contributed to optimizing user experience with tools like SPV wallets and Web3 integrations with experience in testing & writing smart contracts in Cairo.

I will create comprehensive tests for create_listing and cancel_listing, validating state changes, event emissions, and edge cases to ensure reliability. My approach ensures maintainable and scalable test coverage.

ETA : 24hrs

**Comment by 0xLemonn** [comment]
can i tackle this, i would love to contribute here and make my first od contribution.

**Comment by mimiprosper** [comment]
Could I be assigned to this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.
