### ISSUE TITLE
Setup apibara indexer to track land registry events

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#166]
Check the https://www.apibara.com/docs

Track the landregistry events. Setup with postgres.

This is a blocking issue. #183 depends on it.

**Comment by ikemHood** [comment]
I would love to solve this as soon as the ODhack resumes

**Comment by ooochoche** [comment]
May I handle this issue?

**Comment by mimisavage** [comment]
I’d like to help with this.

**Comment by CollinsC1O** [comment]
Can I take this from here?

**Comment by ooochoche** [comment]
I have gone through the docs and can work on the issue

**Comment by ShantelPeters** [comment]
Could I take over this issue?

**Comment by Amarjeet325** [comment]
I'd love to work on this!

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by 0xLemonn** [comment]
can i tackle this, i would love to contribute here and make my first od contribution. i will send a draft pr in 2days max.
