### ISSUE TITLE
Missing Messages When Land Does Not Exist

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#170]
Certain functions are not returning the expected error messages when the land does not exist.

**Steps to Reproduce:**
Call the affected functions with a non-existent land ID.
Observe the lack of expected messages.
**Expected Behavior:**
Functions should return meaningful error messages for non-existent land.
Suggested Solution: Review and update error-handling logic for relevant functions.

**Comment by OWK50GA** [comment]
Hi, @fishonamos
I'm Wilfrid, a Frontend Web Developer adept at writing functions logic and error handling. I can work on this issue by not letting the logic get to the points where they have breaks/breaches, but intercepting before then with error handling.
I'll also have gone over the current error handling logic to see why the problems exist, and that would be crucial in solving them.

**Comment by NueloSE** [comment]
@fishonamos  kindly assign me the above task as i have experience writing smart contracts and test

**Comment by CollinsC1O** [comment]
@fishonamos I will love to take on this and get it done

**Comment by vestor-dev** [comment]
hey @fishonamos i'm new to this repo can i please work on this issue :)

**Comment by Kingsuite** [comment]
Can I take care of this issue?

**Comment by josephchimebuka** [comment]
Mind if I take this issue?

**Comment by Akshola00** [comment]
I’d like to help with this.

**Comment by Unickhub** [comment]
May I pick this up?

**Comment by SoarinSkySagar** [comment]
May I handle this issue @fishonamos ?

I have contributed to the cairo codebase of landver in last odhack too, I am pretty confident I can handle this too.

eta: 2 days

**Comment by Benjtalkshow** [comment]
I’m interested in this one.

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly.  o fix this, I’d review the affected functions to ensure proper checks are in place, add clear error messages like "Land ID not found," and test thoroughly to confirm everything works as expected. This will improve both debugging and user experience. I would really love to be assigned this issue and work on this project.

**Comment by Akshola00** [comment]
Could I grab this task?

I will enhance the error handling mechanism by implementing validation checks to identify non-existent land IDs and create clear error messages for users. My approach includes reviewing each function's error handling logic, introducing specific exception types for land-related errors, and ensuring consistent error reporting to improve usability and debugging.

**Comment by imoleayomi19** [comment]
May I take this issue on?Yes
I am a Front-end developer. I am proficient in CSS, Typescript, JavaScript.
I would love to work on this project and solve the issue.

**Comment by Amarjeet325** [comment]
I'd love to work on this!

**Comment by Supa-mega** [comment]
Can I attempt this issue?

**Comment by suhas-sensei** [comment]
i would like to contribute on this, having experience in js,ts and cairo, i hope i can provide a solution in 24hrs

**Comment by obacollins-lab** [comment]
Would love to tackle this! 
I'm a new contributor

**Comment by mimiprosper** [comment]
Let me handle this issue!  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 4 days.

**Comment by ekumamatthew** [comment]
I'd like to handle this task. I'll handle error response message appropriately

**Comment by fishonamos** [comment]
Hi @NueloSE , If no pr by end of day, we may have to reassign.

**Comment by NueloSE** [comment]
@fishonamos will make a PR today. appologies for the delay
