### ISSUE TITLE
 Function to Determine User Type

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#171]
Create and test a get_user_type function that receives an address and returns a string indicating the user's role ("owner", "inspector",).

**Functionality**:
Input: User address.
Output: User role as a string.

This will help us streamlines role management for improved user experience.

**Comment by CollinsC1O** [comment]
Hi @fishonamos I'm a front-end and blockchain developer, I will love to work on this

**Comment by NueloSE** [comment]
Is it okay if I tackle this?

**Comment by anonfedora** [comment]
Hi I'm Eleazar, a fullstack Blockchain developer,
I will implement an interface, a function and a test (get_user_type) that accepts a contract address as inputand returns a string indicating the user's role ("owner", "inspector",).

Functionality:
Input: User address.
Output: User role as a string.

ETA: 48 Hours

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Josh-121) looking to make first contribution on this project

How I plan on tackling this issue
would impement fuction &
work on feedback & recommendation ensuring contact. Can deliver within few hrs upon assignment

**Comment by GideonBature** [comment]
Can this issue be assigned to me please?

My name is Gideon Bature, a Software Engineer with experience building starknet programmes using Cairo. I also have experience with TypeScript and JavaScript. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by Tronixtek** [comment]
I'd like to handle this task.

**Comment by caxtonacollins** [comment]
please i will liked to be assigned this issue

**Comment by SoarinSkySagar** [comment]
May I handle this issue @fishonamos ?

I have contributed to the cairo codebase of landver in last odhack too, I am pretty confident I can handle this too.

eta: 2 days

**Comment by Benjtalkshow** [comment]
Could I be assigned to this?

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly.  To streamline user role management, I’d create a function that takes a user’s address and returns their role, like "owner" or "inspector." I’d compare the address against a predefined list and return the corresponding role or "unknown" if it’s not found. This would simplify role handling and improve the overall user experience. I would really love to be assigned this issue and work on this project.

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Rust ,Cairo  projects like chainevents , arkprojects , starknet  etc  .   please /assign  this issue .
Thank You

**Comment by imoleayomi19** [comment]
I’m interested in this one. Yes
I am a Front-end developer. I am proficient in CSS, Typescript, JavaScript.
I would love to work on this project.

**Comment by dimka90** [comment]
I am software engineer and blockchain developer, passionate about solving problems.

I can tackle this issue by implementing a function (get_user_type) which will take a user address as input and return the role of the user to improve the user experience and streamline role management.

**Comment by Amarjeet325** [comment]
Can I try solving this issue?

**Comment by Kaminar-i** [comment]
I would like to take on this, and this is how I would go about solving the issue:

I would approach this challenge systematically by first designing a function that takes a contract address as input. To categorize roles, I would define predefined arrays or mappings containing known addresses for each role, such as owners and inspectors. Using these definitions, I would implement logic to compare the input address against the predefined roles. If the address matches the owner list, the function will return "owner". If it matches the inspector list, it will return "inspector". For addresses that do not match any predefined roles, the function will return a default role like "user".

To ensure robustness, I would include error handling to manage unexpected or invalid address inputs gracefully. Finally, I would develop a comprehensive testing strategy to verify the function's correctness across different scenarios, such as valid addresses for each role, addresses that do not belong to any role, and invalid inputs.

**Comment by Supa-mega** [comment]
May I take this issue on?

**Comment by suhas-sensei** [comment]
i have the required expertise in this field and would like to contribute

**Comment by jedstroke** [comment]
Can I try solving this issue?

**Comment by obacollins-lab** [comment]
Let me try this one!
I'm a new contributor
