### ISSUE TITLE
Function to Retrieve Inspectors Added 

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#173]
Create a function to fetch the list of inspectors added using the add_inspector function. This list will help users select an inspector when assigning them to a land using set_land_inspector.

Functionality:
Input: None (fetches all inspectors added).
Output: List of inspectors with relevant details

Why?
Simplifies the process of selecting an inspector for assignment.
Reduces user errors by providing a pre-validated list of available inspectors.

**Comment by Pvsaint** [comment]
Fishon if it pleases you to assign me this issue I'd be very grateful, and I promise open a PR within 48 hours of the assignment.

**Comment by mimisavage** [comment]
I can handle this task , kindly assign.

**Comment by MrRoudyk** [comment]
Could I grab this task? My profile onlydust https://app.onlydust.com/u/MrRoudyk

**Comment by Akshola00** [comment]
I’d like to work on this.

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.
Steps to Implement

1. Contract Changes
Add a public getter function to fetch the list of inspectors.
Store inspector details in a mapping or struct array during the add_inspector function implementation. For example:
	•	Use a mapping(address => Inspector) for individual inspector details.
	•	Use an address[] array to track all inspector addresses for iteration.
Ensure that all added inspectors are properly appended to the list.

2. Fetch Function
Implement a function like getInspectors to return the list of inspectors.
If using Solidity, the function might look like this:
	•	Loop through the stored array of addresses to retrieve inspector details (if necessary).
	•	Return an array of structs containing inspector information.

Expected Outcome

The system will provide a validated list of all added inspectors. This list simplifies the process for users by reducing manual input errors during land inspector assignment.

**Comment by No-bodyq** [comment]
Could I take a shot at this?

**Comment by Unickhub** [comment]
Can I jump on this task?

**Comment by SoarinSkySagar** [comment]
May I handle this issue @fishonamos ?

I have contributed to the cairo codebase of landver in last odhack too, I am pretty confident I can handle this too.

eta: 2 days

**Comment by Benjtalkshow** [comment]
I’d like to work on this.

**Comment by ShantelPeters** [comment]
Let me try this one!

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. To solve this, I’d create a getInspectors function that fetches all the inspectors added via add_inspector. This function would return a list of inspectors with relevant details like name and ID. I’d then use this list in set_land_inspector to allow users to easily select an inspector, reducing errors and simplifying the process.  I would really love to be assigned this issue and work on this project.

**Comment by Michaelkingsdev** [comment]
Can I take this from here?

**Comment by Ekene001** [comment]
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

To Tackle this issue,  I will create a function that fetches the list of inspectors added using the add_inspector function. This will involve querying the database or the relevant data source where inspector information is stored. 

I will ensure that The list will be returned in a structured format, making it easy to use when assigning an inspector to a land via the set_land_inspector function.

By fetching a pre-validated list of available inspectors, I will ensure that users can select from a list of inspectors who have been properly added, reducing errors that could occur from manual input or incorrect selection.

**Comment by mananuf** [comment]
Can I take this from here?

**Comment by imoleayomi19** [comment]
Could I take on this issue? Yes
I am a Front-end developer. I am proficient in CSS, Typescript, JavaScript.
I would love to work on this and solve the issue.

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and javascript, would love to work on this , my ETA is >24Hours and ill create a draft PR in 10 hours time. Thank you for this opportunity. :)

**Comment by Amarjeet325** [comment]
I'd like to handle this task.

**Comment by Supa-mega** [comment]
Mind if I try this one?

**Comment by suhas-sensei** [comment]
gm, Suhas here, having worked in the last od, where  I’ve worked on integrating on-chain mechanics into games and have contributed to optimizing user experience with tools like SPV wallets and Web3 integrations with expertise in writing and testing smart contracts in Cairo.

I will implement fetch_all_inspectors(), retriving prevalidated inspectorr details like ID, name, and availability using an optimized mapping and indexed array. This ensures seamless integration with set_land_inspector and reduces assignment errors. ETA: 24 hours.

**Comment by ekumamatthew** [comment]
Is this issue still available?. let me handle this

**Comment by aspiringLilCoder** [comment]
I'd like to take this issue.
