### ISSUE TITLE
New frontend integration based on new design - big issue

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#174]
We need to setup frontend integration based on our new design. Design will be assigned to the assigned person.

**Comment by Michaelkingsdev** [comment]
Hello @fishonamos 
I am fullstack developer with 4 years of experience. 
Can this task be assigned to me?
I will set up the frontend integration based on the newly provided design. This will involve implementing the UI components and layouts while ensuring responsiveness and alignment with the platform’s style. I’ll integrate any necessary functionalities, follow best practices for maintainable code, and ensure the design is accurately translated into the frontend.

**Comment by Judah04** [comment]
Hi @fishonamos 
I would love to take this task. I am confident that my skills and enthusiasm for frontend development make me well-suited to solve this issue. If assigned, I will ensure timely communication, adhere to best practices, and deliver a high-quality implementation that meets or exceeds expectations.

**Comment by Tzienom** [comment]
Hi, I'm Gabriel and I would love to work on issue #174.

I am a specialized Frontend Developer and I do believe that I do not lack in skill to solve this problem. I shall meet your demands if I am assigned to it.

**Comment by KevinLatino** [comment]
Hello @fishonamos! My name is Kevin Latino, and I'm a frontend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base.  I've also contributed to projects in ecosystems like Starknet and Stellar. 

I would love to contribute to this Issue, I have experience with this kind of issues, i have 2 years of experience in frontend, and I have made landing pages such as https://buildmyevent.xyz/ 

Depending on the design I will finish it in 3-4 days

**Comment by josephchimebuka** [comment]
Hello I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/
May I try this one?

**Comment by Ayoazeez26** [comment]
Can I work on this once the design is completed?

**Comment by mimisavage** [comment]
Can I handle this task?

**Comment by lauchaves** [comment]
Hey! I'm Lau Chaves, and I would like to contribute to this issue!


I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components. I have worked with figma and zeplin

Feel free to check my onlydust profile here and github profile: lauchaves!

**Comment by jorgezerpa** [comment]
Hello! This is how I will atack this issue:

1. Setup a NextJS app
2. Build The UI views following the provided design 
3. Connect with Wallets using Starknet-react 
4. Start contract interactions to fetch and modify data

I'm attentive!!

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by austineblaise** [comment]
Hi [Team/Project Lead],

This is my first time contributing to an OnlyDust project, and I’m excited to help! I can assist with setting up the frontend integration based on the new design, ensuring the UI matches the assigned design and works smoothly.

Looking forward to contributing!

**Comment by emmz3230** [comment]
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.


First, i will understand the design, download the images, use the font used in the design and integrate it based on the design for a better user experience of the project 

will be glad to use my skill pon this 
Thanks

**Comment by Amarjeet325** [comment]
Hi , I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me?

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by Supa-mega** [comment]
I'd be happy to do this.

**Comment by akintola4** [comment]
May I take this issue on? would be really happy to work on it, this is a link to my twitter handle https://x.com/photofola and a link to my recent two works for designers i work with. (https://ooido-kc4l.vercel.app/) & (https://webfleets.vercel.app/)

**Comment by jedstroke** [comment]
I’d like to resolve this.

**Comment by sandragcarrillo** [comment]
I would love to contribute to this issue, I have experience as a frontend developer creating web3 and web3 websites.

**Comment by ekumamatthew** [comment]
May I be assigned to this?. I can assure pixel perfect design full responsive
