### ISSUE TITLE
Implement Login and Signup pages on landing page

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#175]
The figma link contains pages for login and signup, implement those pages but however note a few corrections,  
1. Add a input to take wallet address as a string on signup
2.  Remove social sign on

**Comment by Pvsaint** [comment]
Fishon please let me handle this issue, I can deliver within 72hrs

**Comment by Judah04** [comment]
Hi @fishonamos
If assigned [#174](https://github.com/NoshonNetworks/landver/issues/174), I will ensure a follow up on this and deliver a high-quality implementation that meets or exceeds expectations.

**Comment by MullerTheScientist** [comment]
hello @fishonamos please can i address this issue

**Comment by 0xdevcollins** [comment]
@fishonamos please can I work on this issue? 
I am a Full Stack Blockchain Developer with expertise in Next.js, TypeScript, React, Node.js, and Solidity/Rust. With 46 contributions across 10 OnlyDust projects, I bring technical excellence, adaptability, and a focus on user-centric blockchain solutions.

**Comment by Tzienom** [comment]
Hi, I'm Gabriel and I would love to work on this follow-up issue to issue #174.

**Comment by Ayoazeez26** [comment]
Can I jump on this task once #174 is completed?

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by Unickhub** [comment]
Can I work on this, please?

**Comment by MullerTheScientist** [comment]
hello @fishonamos please can i address this issue

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Mind if I try this one?

**Comment by chibokaxavier** [comment]
I’d like to help with this.

**Comment by ONEONUORA** [comment]
Can I contribute to this one?

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Supa-mega** [comment]
Could I take over this issue?

**Comment by akintola4** [comment]
May I take this issue on? would be really happy to work on it, this is a link to my twitter handle https://x.com/photofola

**Comment by jedstroke** [comment]
May I take this issue on?

**Comment by FemiOje** [comment]
Hello. I am a frontend web developer with 3+ years experience in building fully responsive and efficient web applications from provided design prototypes, among others. I am confident that I can implement the frontend integration if provided with the design files. I am not yet sure of the size of the project, so I may not be able to provide an accurate estimate, but I will ensure that I submit a draft PR within 12 hours of assignment and communicate with the project maintainers regarding my progress and if more clarity is needed.

**Comment by ekumamatthew** [comment]
Can I try solving this issue?

**Comment by melnikga** [comment]
I was waiting for the dependent task to be completed, now I'm starting to work on it.

**Comment by melnikga** [comment]
I still don't have access to the Figma file, could you provide it to me? I've been waiting for it since November 23rd.
