### ISSUE TITLE
Update Design to Fit Current Code Setup

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#176]
The existing design is not fully aligned with the current implementation in the codebase. The design should be updated to accurately reflect the current setup and functionality.

**Steps to Complete:**
Review the current code implementation to understand the existing structure and features.
Compare the codebase with the current design to identify mismatches or outdated elements.
Update the design to align with the codebase.

**Requirements**:
The person working on this issue must have a clear understanding of the current codebase.

**Expected Outcome**
A revised design that accurately represents the current system and provides clear guidelines for further development and user interaction.

**Comment by Osatuyi** [comment]
Can I be assigned this please. I'm a web3 product designer and I can do this.

**Comment by abdegenius** [comment]
Could I take over this issue?I can comfortably handle this issues

**Comment by Unickhub** [comment]
Let me handle this issue!

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by ShantelPeters** [comment]
Can I take this from here?

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. This would be my first time contibuting to this project and i would provide a solution by reviewing the current codebase to understand how things are set up. Then, I’ll compare it with the design to spot any mismatches or outdated elements. Once I know where the issues are, I’ll update the design to better reflect the current implementation. This will ensure everything aligns correctly and provides clear guidelines for future development.  i would really love to be assigned this issue and work on this project.

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.  This is my first time contributing to this project. ETA 48hrs.

**Comment by Amarjeet325** [comment]
I’d like to help with this.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by Supa-mega** [comment]
Mind if I try this one?

**Comment by jedstroke** [comment]
Can I take care of this issue?

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

**Comment by ekumamatthew** [comment]
Could I be assigned to this?.

**Comment by fishonamos** [comment]
Hi @Osatuyi Any updates?

**Comment by Osatuyi** [comment]
> Hi @Osatuyi Any updates?

I'm about to create a pr now, sir.
Thank you.
