### ISSUE TITLE
 Function to Retrieve All Lands with Their Status

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#177]
Create a function to fetch all registered lands along with their current status and other relevant details. 

Functionality:
Input: None (fetches all lands).
Output: A list of land records, each including:
land_id
Owner details (e.g., address or name)
Current status (e.g., "pending approval," "approved," "transferred")
Inspector details (if assigned)
Any other relevant metadata (e.g., area, location)

Why?

Enables easy management and monitoring of all land records.
Simplifies administrative and inspection tasks by providing a single view of all lands and their statuses.
Facilitates integration with frontend or reporting tools for visualization or dashboards.

**Comment by 0xdevcollins** [comment]
@fishonamos Please can I be assign ? I will create a PR in the within the next 24hrs.

I am a Full Stack Blockchain Developer with expertise in Next.js, TypeScript, React, Node.js, and Solidity/Rust. With 46 contributions across 10 OnlyDust projects, I bring technical excellence, adaptability, and a focus on user-centric blockchain solutions.

**Comment by abdegenius** [comment]
Let me try this one!

**Comment by anonfedora** [comment]
Could I try solving this?

**Comment by anonfedora** [comment]
Hi I'm Eleazar, a fullstack Blockchain developer,
I will implement an interface and a function that accepts no input and returns land records containing:
land_id
Owner details
Current status
Inspector details (if assigned)
Any other relevant metadata

ETA: 48 hours

**Comment by ooochoche** [comment]
May I be assigned to this?

**Comment by Akshola00** [comment]
I'd love to work on this!

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of other projects. I would love to work on this.

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by Awointa** [comment]
let me have a go on this

**Comment by caxtonacollins** [comment]
i will love to be assigned this issue. please assign me

**Comment by SoarinSkySagar** [comment]
May I handle this issue @fishonamos ?

I have contributed to the cairo codebase of landver in last odhack too, I am pretty confident I can handle this too.

eta: 2 days

**Comment by Benjtalkshow** [comment]
Can I tackle this one?

**Comment by aguilar1x** [comment]
May I be assigned to this?

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and javascript, would love to work on this , my ETA is >8 Hours and ill create a draft PR in 5 hours time. Thank you for this opportunity. :)

**Comment by ShantelPeters** [comment]
Mind if I try this one?

**Comment by Oshioke-Salaki** [comment]
I'd love to work on this! I am an experienced cairo developer and i would solve this asap.

**Comment by mananuf** [comment]
I'd like to handle this task.

**Comment by imoleayomi19** [comment]
Can I handle this task?Yes
I am a Front-end developer. I am proficient in CSS, Typescript, JavaScript.
I would love to work on this project.

**Comment by mananuf** [comment]
I’m Mananaf, a developer experienced in blockchain and smart contract systems. I've previously worked on a land management solution that tackled issues like land fraud and ownership disputes. For this task, i'll
1. Analyze the smart contracts deployed on the blockchain to understand:
- the data stored (e.g., land ID, owner details, status, inspector details).
- How the data is organized and accessed (e.g., mappings, structs).
- Available methods for retrieving land data.

2. Develop the Fetching Function

Input: None (fetches all lands).
Output: A list of land records in JSON format, including:
land_id
Owner details (e.g., wallet address or metadata from IPFS/other storage if available).
Current status (e.g., "pending approval," "approved," "transferred").
Inspector details (if assigned).
Metadata (e.g., location, area, coordinates).

3. Efficient Data Retrieval
-Implement pagination or batching for scenarios with a large number of records to avoid high gas costs or node timeout issues.

4. Handle Complex Cases
-Handle cases where inspectors or owners are not yet assigned.

With my experience in blockchain development and familiarity with land registry systems, I am well-suited to take on this task. I am confident in my ability to efficiently interact with the blockchain, structure the data, and deliver a robust solution. I am excited about the opportunity to contribute to OnlyDust and bring this feature to life.

**Comment by Amarjeet325** [comment]
I'd like to handle this task.

**Comment by Supa-mega** [comment]
Mind if I take this issue?

**Comment by suhas-sensei** [comment]
gm gm, Suhas here, having worked in the last od, where  I’ve worked on integrating on-chain mechanics into games and have contributed to optimizing user experience with tools like SPV wallets and Web3 integrations.

To solve this issue, I will implement a function to fetch all land records with optimized data retrieval, leveraging structured queries for scalability. The output will include key details such as land ID, owner and inspector info, status, and metadata. I’ll ensure efficient handling of large datasets using pagination and account for edge cases like unassigned inspectors, delivering a robust and future-proof solution.

**Comment by guha-rahul** [comment]
May I try my hand at this? I have some experience in cairo and i think i can get it done

**Comment by obacollins-lab** [comment]
Can I be assigned to this? I'm a new contributor

**Comment by ekumamatthew** [comment]
I'd like to take this issue.. I create a function that fectches all registered lands along with their current status and other relevant details.
