### ISSUE TITLE
Remove Land Registration Fee

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#178]
The land registration fee mechanism is currently implemented but needs to be removed as part of the updated requirements.

**Steps to Complete:**

- Identify and remove all instances of the registration fee logic in the contract code (e.g., calculations, validations, and storage updates related to fees).
- Update any functions dependent on the registration fee to ensure they work seamlessly without it.
- Review and update tests to remove assertions or conditions related to the registration fee.
- Ensure that the frontend and Voyager interactions align with this change.

**Expected Outcome:**
Land registration no longer involves a fee.
All dependent logic and tests are updated to reflect the removal of the fee.

**Comment by abdegenius** [comment]
Will love to help out with this!

**Comment by CollinsC1O** [comment]
Hello @fishonamos I will love to work on this, please assign

**Comment by Kingsuite** [comment]
Can I take this from here?

**Comment by mimisavage** [comment]
Can I try solving this issue?

**Comment by 0xdevcollins** [comment]
Can I work on this, please?

My Background
I am a Full Stack Blockchain Developer with proficiency in Solidity/Rust, Next.js, TypeScript, React, and Node.js. I've demonstrated my ability to adjust to a variety of requirements, perform well under pressure, and reliably produce user-centric blockchain solutions with 46 significant contributions spread over 10 OnlyDust projects.

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

Steps to Complete

1. Identify and Remove Registration Fee Logic
	•	Examine the contract code for all instances where the registration fee is calculated, validated, or stored.
	•	Remove these instances, ensuring no references to the fee remain.
	•	Typical areas to check:
	•	Constructor or initialization logic.
	•	Functions handling registration and fee deduction.
	•	Storage variables related to the fee.

2. Update Dependent Functions
	•	Identify functions relying on the registration fee.
	•	Adjust their logic to ensure seamless functionality without the fee.
	•	Replace or remove input parameters, condition checks, and state updates related to the fee.

3. Review and Update Tests
	•	Locate tests that include assertions or conditions for registration fees.
	•	Modify or remove such tests to reflect the updated logic.
	•	Ensure all tests pass after the changes.
	•	Add new tests if necessary to validate the updated behavior.

4. Frontend and Voyager Updates
	•	Check the frontend for any UI elements or API calls referencing the fee.
	•	Update or remove these references to match the updated backend logic.
	•	Test interactions with Voyager (or any blockchain explorer) to ensure smooth operation without fee-related dependencies.

Expected Outcome

	•	Land registration no longer involves a fee.
	•	Smart contract logic is clean, without references to the registration fee.
	•	Tests are updated, and all pass successfully.
	•	Frontend and Voyager interactions work as expected, aligning with the updated requirements.

**Comment by caxtonacollins** [comment]
Can I contribute to this one? ETA 24 hours

**Comment by SoarinSkySagar** [comment]
May I handle this issue @fishonamos ?

I have contributed to the cairo codebase of landver in last odhack too, I am pretty confident I can handle this too.

eta: 2 days

**Comment by Benjtalkshow** [comment]
I’d like to work on this.

**Comment by casweeney** [comment]
## Tackling this issue:

I will rewrite the fee model with an optimised logic to keep the fee as minimal as possible, I will research for the best approach of fee model implementation.

## ETA: 8-10 hours

**Comment by akintewe** [comment]
Hello can i be assigned this issue, i am a new contributor with experience in Cario and javascript, would love to work on this , my ETA is >8 Hours and ill create a draft PR in 7 hours time. Thank you for this opportunity. :)

**Comment by austineblaise** [comment]
Hi [Team/Project Lead],

This is my first time contributing to an OnlyDust project, and I’m excited to help! I can remove the registration fee logic from the contract code, update related functions, and adjust tests to match the changes. I’ll also ensure the frontend and Voyager work smoothly without the fee.

Looking forward to contributing!

**Comment by ShantelPeters** [comment]
Is it okay if I take this?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo project like chaineventt , arkproject etc   .   please /assign  this issue .
Thank You

**Comment by chibokaxavier** [comment]
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. This would be my first time contibuting to this project and i would provide a solution by identifying and removing all instances of the fee related logic in the contract code, such as calculations, validations, and storage updates. Next, I would update any functions that depend on the fee to ensure they work without it. After that, I'd review and update the tests to reflect the removal of the fee. Finally, I would make sure that the frontend and Voyager interactions align with this change to provide a seamless user experience.  i would really love to be assigned this issue and work on this project.

**Comment by Michaelkingsdev** [comment]
I'd like to take this issue.

**Comment by Amarjeet325** [comment]
I’m interested in this one.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and a blockchain dev 
i would really love to contribute to your project 
please kindly assign :)

**Comment by Supa-mega** [comment]
Can I contribute to this one?

**Comment by suhas-sensei** [comment]
gm gm, Suhas here, having worked in the last od, where  I’ve worked on integrating on-chain mechanics into games and have contributed to optimizing user experience with tools like SPV wallets and Web3 integrations.

 I will systematically remove the registration fee logic by mapping dependencies, isolating related calculations, and refactoring impacted functions to ensure seamless operations. I’ll also update test cases and audit the frontend and Voyager interactions to align with the updated requirements for a fee-free registration process.

**Comment by ekumamatthew** [comment]
Can I contribute to this one?
