### ISSUE TITLE
Build and Modify Reusable Components Based on the Design

### ISSUE THREAD

**Issue by GoSTEAN** [NoshonNetworks/landver#180]
### Description 
We need to ensure our components are reusable and match the design guidelines for a consistent look and feel.

### Tasks:

Update the existing P (Paragraph), Modal, and Input components to align with the style guide (we should be able to switch styles using a variant prop).
Add a new reusable Table component with basic features like sorting and pagination.
Make sure all components follow the typography, spacing, and color rules outlined in the design.
Write clear and simple documentation for using these components

**Comment by 0xdevcollins** [comment]
@fishonamos Please kindly assign :) I will make a PR in the within 24hrs

I am a Full Stack Blockchain Developer with expertise in Next.js, TypeScript, React, Node.js, and Solidity/Rust. With 46 contributions across 10 OnlyDust projects, I bring technical excellence, adaptability, and a focus on user-centric blockchain solutions.

**Comment by mimisavage** [comment]
I'm confident in my ability to deliver excellent results here. May I take it on?

**Comment by Pvsaint** [comment]
Hi Fishon, please assign me this task, I promise to deliver within 48 hours, if not, assign someone else.
I'm a frontend and smart contract developer.

**Comment by vestor-dev** [comment]
hey @fishonamos can i work on this issue and get it done 
kindly assign thanks

**Comment by martinvibes** [comment]
hey @GoSTEAN @fishonamos can i work on this?

**Comment by abdegenius** [comment]
I’d like to resolve this.

**Comment by Tzienom** [comment]
Hi, I'm Gabriel and I would love to work on issue #180.

I am a specialized Frontend Developer and I am well-skilled to solve the problems you require. I can easily accomplish building reusable styles using Styled Components and making customizable, any prop that might need to change in the future.

**Comment by Akshola00** [comment]
Can I attempt this issue?

**Comment by Yunusabdul38** [comment]
I'd love to work on this issue.
and make sure it meets the requirements

**Comment by caxtonacollins** [comment]
i will love to be assigned this issue. please assign me

**Comment by Supa-mega** [comment]
I’m interested in this one.

**Comment by deeseeker** [comment]
I am applying to this issue via OnlyDust platform.

Hi, I'm Qudus Adeyemi, a front-end developer with 2 years of experience. I had the opportunity to contribute to the previous OD Hackathon, where I improved the Starknet React documentation and developed a useWatchAssets hook to enhance wallet tracking functionalities and I have also contributed to Starknet Quest. I enjoy learning and tackling new challenges, and I see tackling this issue as a great way to deepen my understanding of dApps while contributing to the project.
For this issue, I estimate it will take around 1-2 days to complete, and I'm excited to dive into the task and collaborate with the team!

To tackle this issue, I will be doing the following:

Install shadcn table because it fits well with the project setup to handle filtering, pagination, sorting and updates when user performs any action. it's also lightweight.

Implement features:
Reusable component.
Pass the style props based on the variable set in the tailwind config file
write a clear docs for using the components
Pay attention to responsiveness and interactivity and other specs

**Comment by Benjtalkshow** [comment]
I'd like to handle this task.
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 45 contributions to over 15 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

MY ETA is 48hrs. Thanks

**Comment by austineblaise** [comment]
Hi [Team/Project Lead],

This is my first time contributing to an OnlyDust open-source project, and I’m excited to help! I can update the P, Modal, and Input components to match the style guide and add a reusable Table with sorting and pagination. I’ll ensure everything follows the design rules and write simple documentation to make the components easy to use.

Looking forward to contributing!

**Comment by ShantelPeters** [comment]
Mind if I try this one?

**Comment by Jethrolopwus** [comment]
Can I work on this, please?

**Comment by Michaelkingsdev** [comment]
Can I be assigned to this?  I am an experienced frontend developer with 3 years of experience.  This is my first time contributing to this project. ETA 48hrs.

**Comment by ONEONUORA** [comment]
Can i work on this.

**Comment by melnikga** [comment]
Can I contribute to this one?
Hi, my name is Georgiy, I'm a fullstack blockchain developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

**Comment by Jethrolopwus** [comment]
Hi, my name is Jethro Lopwus a front end develooper. I intend to achieve this task by dynamically creating and implementing  the reusable components based of the design and ensure it follows the consistent look on the ui using react.js next.js. components

**Comment by LazarusAA** [comment]
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️ with experience in both front-end and back-end development, and I would love to tackle this issue. With my proficiency in TypeScript, JavaScript and experience working on the front-end aspects of my last few hackathons, I'm confident that I can contribute to this project efficiently.

My workflow:

- Update ```P```, ```Modal```, and ```Input``` components to support style variants.
- Create a reusable ```Table``` component with sorting and pagination.
- Align all components with typography, spacing, and color guidelines.
- Write concise documentation for component usage.

ETA: 48 hrs

**Comment by Amarjeet325** [comment]
I'd love to work on this!

**Comment by jedstroke** [comment]
Can I be assigned to this?

**Comment by ekumamatthew** [comment]
Is this issue still available?. I would love to handle this.

**Comment by aspiringLilCoder** [comment]
I'd love to give this a go.
