### ISSUE TITLE
Audit land registry and nft cairo tests

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#182]
A lot of the cairo tests donot cover the edge cases. Review the tests and add additional edge cases where necessary.

**Comment by ekumamatthew** [comment]
I'd like to take this issue. let me handle task

**Comment by Akshola00** [comment]
Can I take care of this issue?
I'm Akinshola Akinniyi
A smart contract dev and tester 
I would like to take on this issue 
Checking all the test and adding additional test for edge cases to ensure security and safety of assets on this protocol
Thanks

**Comment by mananuf** [comment]
I’d like to work on this using the TDD approach to conform to the 3 A's of testing 
-Arrange
-Act
-Assert
to cover more edge cases on the test
