### ISSUE TITLE
Setup a backend routes for Land events

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#183]
Setup an express server that will query the land events indexed in #166 

getlands, getinspectors, getapproved lands, verify lands(takes landid and returns true if land is verified), tranfer history etc.

**Comment by ekumamatthew** [comment]
Could I take on this issue?

**Comment by GoSTEAN** [comment]
Can I work on this?

**Comment by Birdmannn** [comment]
Hi @fishonamos I just went through the apibara indexer docs and I can handle this issue
