### ISSUE TITLE
Latitude and longitude should be picked from map on land registraion

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#240]
For register land on frontend, users should be able to add longitude and latitude with a map picker.

**Comment by sonkeydotcom** [comment]
Hello. Id love to take on this task. ETA 48hrs 

I’m an experienced software engineer, with experience in both FE, BE and mobile development. First time contributor

**Comment by MarcusDavidG** [comment]
Would love to contribute to this one...as I am working on something similar that has to do with map integrations for live tracking.

**Comment by fishonamos** [comment]
@MarcusDavidG ? Any updates. We need to free this for other contributors.

**Comment by MarcusDavidG** [comment]
@fishonamos Sorry about the delay, raising a PR tonight.

**Comment by sonkeydotcom** [comment]
Can I work on this. ETA 48hrs
