### ISSUE TITLE
update verify lands to lands in frontends

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#241]
https://demo.landver.net/verify-land

Instead of verify land, it should just be "lands". It will show all the lands for an inpector. Both pending and approve.

<img width="1440" alt="Screenshot 2024-12-14 at 05 21 46" src="https://github.com/user-attachments/assets/5684545d-d27c-4760-ab04-5313e9aec8ee" />

**Comment by OWK50GA** [comment]
Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue.

My approach:
I'll go to the component that renders the side bar and change the title to 'Lands' from 'Verify Lands'. 
Then I'll go inside the component, which would show lands that are not verified and I'll tweak the code to make it show all lands as well as their verification status

Expect my first PR within 24 hours

**Comment by emarc99** [comment]
With my experience of FE technologies (React vite, tailwind, nextjs, shadcn) and understanding of your codebase. 
I can do this in 1 day.

**Comment by od-hunter** [comment]
Hi @fishonamos , can I be assigned this issue please? I would love to be the given the opportunity to solve this issue please. I have experience in html, css, JavaScript, TypeScript and cairo.

I’ll push a meaningful pr in 1 day
Kindly assign me please I’m up for the task.

**Comment by wheval** [comment]
Hello @fishonamos, I'm Wheval an experienced Frontend Developer.

I can get this done ASAP.

Please assign. This would be my first contribution to Landver.
Thank you!

ETA is 4hrs.

**Comment by Birdmannn** [comment]
Please can I handle this?

**Comment by Prosper1218** [comment]
let me fix this for you !!
I'll make my PR within 4-6hrs.
I'm a FrontEnd developer with years of experience.
