### ISSUE TITLE
Ensure Logged-In Users cannot access landing page

### ISSUE THREAD

**Issue by Solomonsolomonsolomon** [NoshonNetworks/landver#242]
Currently, when a user logs in from the landing page, they are redirected to the dashboard. However, logged-in users can still access the landing page by navigating back manually or typing the URL. This feature should ensure that once a user is logged in, they cannot access the landing page and are always redirected to the dashboard. This is a fullstack issue not just a frontend one

**Comment by Xaxxoo** [comment]
Hi, should I go on and handle this?

**Comment by fishonamos** [comment]
Any updates @Xaxxoo . We need this.

**Comment by OWK50GA** [comment]
Hi, I can also do this, just in case

**Comment by Xaxxoo** [comment]
> Any updates @Xaxxoo . We need this.

I just created a pull request sir.
