### ISSUE TITLE
Sync font sizes in landing page

### ISSUE THREAD

**Issue by Solomonsolomonsolomon** [NoshonNetworks/landver#263]
Currently, there is an inconsistency in the font sizes used across the application. Specifically:

The font size on the landing page is set to font-xs.
The font size on the sign-in and sign-up pages is different, creating a mismatch.
This inconsistency impacts the user interface, making it less visually appealing and potentially confusing to users.

Review the font sizes across the entire application.Identify and set a uniform font size that enhances the UI and ensures a cohesive design.Test the chosen font size across all pages to ensure visual consistency and user-friendliness

**Comment by SudiptaPaul-31** [comment]
Would love to work on this issue

Approach:
I will start by checking where are text files are present and will check it respective css properties and then making the changes in the font size and any other changes if requires

**Comment by NueloSE** [comment]
Could I take a shot at this?

**Comment by Amarjeet325** [comment]
I’d like to work on this.

**Comment by No-bodyq** [comment]
May I be assigned to this?

**Comment by jaiminRaiyani** [comment]
Could I be assigned to this?

**Comment by GideonBature** [comment]
Could I take on this issue?

My name is Gideon Bature, with experience working with JavaScript/TypeScript. If assigned, I should send my first PR within 24 hours.

Thank you!

**Comment by ONEONUORA** [comment]
Mind if I try this one? I am full stack and block chain developer. Good at creating pixel perfect  and unique font size applications. I love to work on this

**Comment by sonkeydotcom** [comment]
May I be assigned to this?

**Comment by BigBen-7** [comment]
Can I take this from here?

**Comment by dimka90** [comment]
Can I work on this, please? I will deliver on this if given the opportunity

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by jaykayudo** [comment]
Can i work on this?

I am experienced full stack developer and i believe i can handle this task.

**Comment by ekumamatthew** [comment]
Is this issue still available? I can fix this ASAP.

**Comment by pheobeayo** [comment]
Could I take over this issue?

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer and UI UX designer with strong foundation in modern web development frameworks and technologies. My expertise includes: Figma Nuxt.js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. I would love to contribute to this project.

**Comment by Shalomnze** [comment]
I am Nze Shalom, a full stack developer and UI UX designer with strong foundation in modern web development frameworks and technologies. My expertise includes: Figma Nuxt.js, Next.js and Tailwind CSS with a bit of knowledge in Cairo. I am Experienced in crafting responsive, visually appealing designs using Tailwind CSS, ensuring consistency and efficiency in the development process. I would love to contribute to this project. ETA is 12hrs

**Comment by davedumto** [comment]
Hi,
My name is David, and I am a frontend developer skilled in JavaScript, TypeScript, React.js, Next.js, and Tailwind CSS. I will review and standardize font sizes across the application to ensure a cohesive and visually appealing design.
I’ll identify inconsistencies, set a uniform font size, and test thoroughly across all pages to enhance the UI and improve user experience. ETA: 5 hours

**Comment by martinvibes** [comment]
Could I try solving this?
I'm a frontend developer and blockchain dev
I would love to work on this

**Comment by Birdmannn** [comment]
Good morning dev, can I handle this? I have good experience in UI dev.

**Comment by Solomonsolomonsolomon** [comment]
@Shalomnze Any updates?

**Comment by Akshola00** [comment]
@Solomonsolomonsolomon would love to work on this issue if you would assign 
I'm confident I can handle this
ETA 12 hrs

**Comment by Solomonsolomonsolomon** [comment]
@davedumto  are you still available for this?

**Comment by No-bodyq** [comment]
Hello @Solomonsolomonsolomon, I'm available for this

**Comment by davedumto** [comment]
@Solomonsolomonsolomon I'm available

**Comment by davedumto** [comment]
> @davedumto are you still available for this?

I am available, kindly assign me so I work on it

**Comment by Solomonsolomonsolomon** [comment]
@davedumto assigned, will need a PR ASAP,

**Comment by davedumto** [comment]
@Solomonsolomonsolomon , I have made a PR, Kindly look through it. Thanks
