### ISSUE TITLE
Add a workflow to the project. 

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#34]
The workflow should check:

scarb fmt
scarb build
scarb test

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @Solomonsolomonsolomon  for code, infrastructure

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @GoSTEAN for code
@all-contributors please add @rajiabdul  for

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @rajiabdul for doc
@all-contributors please add @GoSTEAN  as contributor

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @GoSTEAN for code
