### ISSUE TITLE
Test update land and reject land

### ISSUE THREAD

**Issue by mubarak23** [NoshonNetworks/landver#50]
Test the following functions:

Update land
reject land

Implement and test logic for add_inspector and  and remove inspector

**Comment by Akshola00** [comment]
@mubarak23 please assign this to me

**Comment by juandiegocv27** [comment]
Hi @mubarak23, please assign me this issue, it is available? could you give a better description please, I really like this project😎

**Comment by Yunusabdul38** [comment]
Let me handle this issue!

**Comment by SoarinSkySagar** [comment]
I already have experience in working on this codebase (including the tests), and would very much like to work on this one.
Will have multiple testcases and make sure every one of the tests pass for the 4 given functions

**Comment by jaiminRaiyani** [comment]
I'd be happy to do this.

**Comment by sandragcarrillo** [comment]
Could I take a shot at this?
