### ISSUE TITLE
trim PR template

### ISSUE THREAD

**Issue by Solomonsolomonsolomon** [NoshonNetworks/landver#54]

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Can I be assigned this issue?

**Comment by akintewe** [comment]
@Solomonsolomonsolomon Can i work on this please

**Comment by pheobeayo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest

### How I plan on tackling this issue
My Approach includes:
- By thoroughly reading the current documentation and the current template for PR.
- Identify the compelling points in the template.
- Trim the PR to be concise.
- Create a PR.
- Request for a Review
- Make changes based on the Review of the PR.
