### ISSUE TITLE
Initialize TypeScript SDK

### ISSUE THREAD

**Issue by Solomonsolomonsolomon** [NoshonNetworks/landver#55]
We need to set up the initial structure for our TypeScript SDK. This issue will focus on defining the required methods and the overall architecture without delving into the actual implementation.
The required methods as well as their arguments can be found in the land registry

**Comment by Jemiiah** [comment]
@Solomonsolomonsolomon i would love to work on this issue if it open for contributions

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Can I be assigned this issue? I'll deliver as soon as possible

**Comment by Benjtalkshow** [comment]
Hello @Solomonsolomonsolomon 
Can this issue be assigned to me? This is my first time of contributing to this project. I will deliver a quality work. Thanks.

**Comment by fishonamos** [comment]
@0xdevcollins @Jemiiah @Benjtalkshow . Will let you know when new issues come in.

**Comment by Jemiiah** [comment]
Alright sure thanks ser @fishonamos

**Comment by 0xdevcollins** [comment]
Okay thanks 
> @0xdevcollins @Jemiiah @Benjtalkshow . Will let you know when new issues come in.

**Comment by martinvibes** [comment]
Hello @fishonamos I would love to participate too :)

**Comment by Benjtalkshow** [comment]
> @0xdevcollins @Jemiiah @Benjtalkshow . Will let you know when new issues come in.

Alright. Thanks
