### ISSUE TITLE
Add a scarb fmt pre-commit hook

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#61]
Add a precommit hook to check that cairo codes are correctly formatted before they are pushed.

**Comment by Jemiiah** [comment]
@fishonamos Is this open for contribution ? or still a self work

**Comment by fishonamos** [comment]
Can you do it? @Jemiiah

**Comment by Jemiiah** [comment]
I can do it @fishonamos how urgent do you need it done ser

**Comment by Jemiiah** [comment]
creating a PR soon

**Comment by Jemiiah** [comment]
@fishonamos created a PR ser
