### ISSUE TITLE
Enhance Land Use Enumeration

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#81]
Task: Expand the LandUse enum to include more specific categories and implement a way to easily add new categories in the future.

Definition of Done:
•  The LandUse enum is expanded with at least 5 new specific categories.
•  A mechanism is implemented to allow adding new categories without breaking existing functionality.
•  The land registration and update functions are modified to accommodate the new categories.
•  Tests are updated to cover the new land use types.

Note: Only applications through the OnlyDust platform will be considered.

**Comment by KevinMB0220** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
As part of Dojo Coding, I'll expand the **LandUse enum** by adding at least 5 new specific categories and implement a mechanism that allows adding new categories easily in the future without affecting the current functionality. I'll also modify the land registration and update functions to handle the new categories, and ensure the tests are updated to cover these additions.

**Comment by zleypner** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi! I’m Anwar a Software Developer with +3 years of experience, and I would love 
to make my first contribution to this project. I'm also a member of the Dojo Coding community CR.

### How I plan on tackling this issue
I will add at least five new specific categories to the LandUse enum and create an easy way to add more categories in the future. I will also update the land registration and update functions to include these new categories and make sure the tests cover all of them.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello, i'm a frontend and blockchain developer, i will love to work on this issue.

### How I plan on tackling this issue
- I will add at least 5 new specific categories to the LandUse enum. 
- I will implement a mapping or an array to allow for dynamic management of land use categories. This can involve a structure to hold the categories and a function to add new ones without breaking existing functionality.
- I will update the land registration and update functions to accommodate the new categories. This may involve changing the data types used in those functions to reflect the new LandUse structure.
- I will ensure that the tests are updated to cover the new land use types. This will include creating tests to verify that the new categories can be added and that the registration function correctly handles them.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity, participated in ODHacks since 7.0 as part of my involvement with Dojo Coding. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
1. Identify five specific categories to add to the LandUse enum
2. Instead of hardcoding the enum values, use a mapping or an array to store land use types, which allows for easier addition of new categories in the future
3. Ensure that existing functionality that depends on the LandUse enum is preserved. 
4. Update any existing tests to include cases for the new land use categories

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have a strong background in software development, with a focus on smart contract development and full-stack web applications. My experience includes working with TypeScript and implementing enums and similar constructs in various projects, which gives me a solid foundation for expanding the LandUse enum and ensuring that the application remains stable and maintainable. Additionally, I have expertise in writing unit tests and creating comprehensive documentation, which will be beneficial for updating tests to cover new land use types.

### How I plan on tackling this issue
Expand the LandUse Enum:

I would first identify and define at least five new specific categories to add to the existing LandUse enum, ensuring they are clearly distinct and meaningful (e.g., Residential, Agricultural, Commercial, Industrial, Recreational).
Implement a Mechanism for Adding Categories:

To allow for future expansion of the enum without breaking existing functionality, I would consider using a configuration-based approach. This could involve:
Storing land use categories in a separate configuration file (e.g., JSON or YAML) that can be read at runtime.
Creating a factory or service class responsible for managing land use categories, which can facilitate the addition of new categories dynamically.
Modify Land Registration and Update Functions:

I would review the existing land registration and update functions to accommodate the new categories, ensuring they can handle both the old and new categories without issues.
This might involve updating data validation logic to check for valid land use types and modifying the data models to include the new enum values.
Update Tests:

I would write new unit tests to ensure that the new categories are correctly integrated into the land registration and update processes. These tests would cover:
Successful registrations with the new categories.
Error handling for invalid categories.
Compatibility with existing functionality to ensure no regressions occur.
Documentation:

Finally, I would update any relevant documentation to reflect the changes made, including an overview of the new land use categories and instructions for adding future categories.

**Comment by fishonamos** [comment]
@Akshola00 . This is needed urgently. Please can you do it by EOD?

**Comment by Akshola00** [comment]
yes @fishonamos 
ive started work already
