### ISSUE TITLE
Implement Metadata URI for Land NFTs

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#85]
Task 1.: Enhance the LandNFT contract to include a metadata URI for each NFT, allowing for off-chain storage of additional land information.

Definition of Done:
•  The LandNFT contract is updated to include a metadata URI for each token.
•  A function is added to update the metadata URI.
•  The tokenURI function is implemented to return the metadata URI.
•  Tests are written to verify the new functionality.

Task 2. Implement NFT Locking Mechanism for Land Transfers
Description:
Create a locking mechanism for Land NFTs to prevent transfers during pending land transactions or disputes.
Tasks:
Add a locked status to the NFT contract
Implement lock and unlock functions in the ILandNFT trait
Update the transfer function to check for locked status before allowing transfers
Modify the LandRegistry contract to lock NFTs when a land transfer is initiated
Implement unlocking mechanism after successful transfer or cancelled transaction
Add events for locking and unlocking NFTs
Write tests for the locking mechanism and its integration with land transfers

Note: Only applications through the OnlyDust platform will be considered.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
To address this issue, I will enhance the LandNFT contract by adding a storage field that maps each token_id to its corresponding metadata URI. I will implement a new function that allows only authorized entities (likely the land registry contract) to set or update the metadata URI for each token. The tokenURI function will then be implemented to return the URI for a given token_id. I will ensure that the implementation is gas-efficient and integrates smoothly with the existing ERC721 logic. Finally, I will update the test suite to verify that the metadata URIs are correctly set, retrieved, and that only authorized updates are allowed.

ETA - 2 days

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello can I work on this

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, I am a skilled cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement. this is issue is similar to something i've worked on in the past so, it's a perfect fit for me.

### How I plan on tackling this issue
I'll be using the standard erc4906 to achieve this to ensure compatibility. then i'll write test to ensure it functions as expected.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue, I’ll take the following the steps:
1.⁠ ⁠I’ll add metadata URI storage-that is I’ll introduce a mapping to store metadata URIs for each token.
2.⁠ ⁠I’ll create a function to update the URI, restricted to the owner or authorized role.
3.⁠ ⁠Next, I’ll implement the ⁠ tokenURI ⁠ function to retrieve the stored URI.
4.⁠ ⁠Then I’ll create tests to validate the setting and retrieval of metadata URIs.

Please assign me, I’m ready to work.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello, i'm a frontend and blockchain developer, pls i will love to work on this issue

### How I plan on tackling this issue
- I will enhance the LandNFT contract to include a metadataURI variable that stores the URI for each NFT.
- i will Implement Lock and Unlock Functions
-I will Update Transfer Function
- i will Modify LandRegistry Contract 
- I will Implement Unlocking Mechanism

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past.

### How I plan on tackling this issue
I will carefully implement the feature as requested and add all the necessary tests.

**Comment by 0xNeshi** [comment]
@fishonamos thanks for the opportunity to contribute. 
I noticed the issue was labeled as "Blocked", should I hold off on working on it for now?
