### ISSUE TITLE
Implement and test getlandcount and getlandby owner functions

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#86]
Ensure the logic works and is well tested

```
fn get_land_count(self: @TContractState) -> u256;
fn get_lands_by_owner(self: @TContractState, owner: ContractAddress) -> Array<u256>;

```
Definition of Done:
•  Tests are written to verify the new functionality.

Note: Only applications through the OnlyDust platform will be considered.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a web3 developer

### How I plan on tackling this issue
I will Implement `get_land_count` and `get_lands_by_owner` functions, and ensure they work correctly. Write tests to verify the functionality of both methods.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Am a frontend developer with some experience in writing smart contract and testing smart contract in cairo and solidity.

### How I plan on tackling this issue
- I would create suitable test case for each function and test the contract state before and after the function call. previous test from ODhack 8.0 [scaffold testing](https://github.com/Scaffold-Stark/scaffold-stark-2/issues/291)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer. I will love to solve this issue. Please assign

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a Blockchain developer with expertise in Cairo, Solidity, and Rust. I have experience in developing and testing smart contracts, contributing to projects like Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge.

### How I plan on tackling this issue
[1]=>Implement get_land_count to return the total number of lands.
[2]=>Implement get_lands_by_owner to retrieve land IDs for a specific address.[3]=>Write unit tests for both functions to ensure correctness.
[4]=>Integrate tests into the existing suite for seamless execution.
[5]=>Please assign me, Sir/Madam.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
i wll Define the getLandCount function to return the total number of lands.
Define the getLandByOwner function to return a list of land IDs owned by a specific address.
 i wiil Test getLandCount with existing lands.
Test getLandByOwner with existing lands and a valid owner address.
Test getLandByOwner with a non-existent owner address.
Test getLandCount with no lands added.

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
GM @fishonamos, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, Cairo and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
I would approach the problem like this:
 - Check out the  `land_registry/src` folder and check all available structs for the available fields
 - Create the function interfaces in `land_registry/src/interface.cairo`. The updated snippet will be like this:
```
#[starknet::interface]
pub trait ILandRegistry<TContractState> {
    fn register_land(
        ref self: TContractState, location: felt252, area: u256, land_use: LandUse,
    ) -> u256;
    fn transfer_land(ref self: TContractState, land_id: u256, new_owner: ContractAddress);
    fn get_land(self: @TContractState, land_id: u256) -> Land;
    fn update_land(ref self: TContractState, land_id: u256, area: u256, land_use: LandUse);
    fn approve_land(ref self: TContractState, land_id: u256);
    fn reject_land(ref self: TContractState, land_id: u256);
    fn is_inspector(self: @TContractState, address: ContractAddress) -> bool;
    fn add_inspector(ref self: TContractState, inspector: ContractAddress);
    fn remove_inspector(ref self: TContractState, inspector: ContractAddress);
     fn get_land_count(self: @TContractState) -> u256;
     fn get_lands_by_owner(self: @TContractState, owner: ContractAddress) -> Array<u256>;  
}
```
 - Define the functions in `land_registry/src/land_register.cairo`
 - Update the tests and add testcases to include the new components in `land_registry/tests/test_land_register.cairo`
 - Ensure that all tests are passing and code is neat and clean and then create the PR

## ETA: 2 Days

**Comment by DiegoB1911** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, and becoming a part of this project.

### How I plan on tackling this issue
To solve this, I will:
1. Understand the requirements of each function.
2. Plan the contract structure.
3. Implement the functions.
4. Write tests.
5. Document the code.

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To ensure the logic for `get_land_count` and `get_lands_by_owner` functions works effectively, I will start by implementing unit tests for both functions. For `get_land_count`, I will verify that it accurately returns the total number of lands associated with the contract. For `get_lands_by_owner`, I will test that it correctly returns an array of land IDs owned by a specified `ContractAddress`. Additionally, I will include edge cases, such as testing with an owner address that has no lands, to confirm that the function handles such scenarios gracefully. Finally, I will ensure that all tests pass successfully before considering the implementation complete.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo. I am good at tests.

### How I plan on tackling this issue
To solve this issue in just 3 steps:
1.⁠ ⁠I’ll ensure get_land_count and get_lands_by_owner are implemented correctly.
2.⁠ ⁠Next, I’ll create test cases covering various scenarios for counting lands and retrieving lands by owner.
3.⁠ ⁠Lastly, I’ll execute the tests to verify that the logic works as expected

Please assign me, I’m ready to work.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past.

### How I plan on tackling this issue
I will carefully implement the feature requested and write tests to make sure the functionality is working properly with 100% coverage.

ETA 1 day.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
hello, i'm a frontend and a blockchain developer,  i would love to work on this task

### How I plan on tackling this issue
I would  take a look at the requirement and follow it exactly to make sure that i complete everything and leave no stone unturned. i would first go through the codebase to understand the project and coding style
