### ISSUE TITLE
Implement and test is_land_approved and get_land_transaction_history functions 

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#87]
Ensure the logic works and is well tested

```
 fn get_land_transaction_history(self: @TContractState, land_id: u256) -> Array<(ContractAddress, u64)>;
 fn is_land_approved(self: @TContractState, land_id: u256) -> bool;
```

Implement a get_pending_approvals function that returns an array of land IDs awaiting approval.

Definition of Done:
• Tests are written to verify the new functionality.

Note: Only applications through the OnlyDust platform will be considered.

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full-stack and web3 developer with experience in cairo

### How I plan on tackling this issue
I will implement the get_land_transaction_history and is_land_approved functions and ensure they work correctly by writing unit tests to verify their functionality

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
As a Computer Science graduate with hands-on expertise in JavaScript, TypeScript, and Cairo, I bring a strong foundation in both theoretical and practical development. My academic background has provided me with good problem-solving skills and comprehension of data structures, which is critical for creating smart contract tasks.

### How I plan on tackling this issue
First, I'd look into the contract's state management criteria for land approval status and transaction history. The is_land_approved function would be designed with great attention to access constraints and state validation. For get_land_transaction_history, I would ensure that transaction records are stored and retrieved efficiently while maintaining historical data integrity.
Testing would be comprehensive but focused, beginning with unit tests for fundamental functionality and gradually growing to include edge situations and significant security problems. Having worked with strongly-typed languages, I am familiar with Cairo's type system and recognize the significance of extensive testing in smart contract development.
I'm excited to contribute to this project and learn from my experiences while providing dependable, well-tested code.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer. I will love to work on this issue. It is something I can handle

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a Blockchain developer with expertise in Cairo, Solidity, and Rust. I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more.

### How I plan on tackling this issue
[1]=>Write a test to confirm that the event count increases when a new event is added.
[2]=>Create another test to verify that the appropriate event is emitted when an event is successfully added.
[3]=>Ensure that both tests are integrated with the existing test suite for seamless execution.
[4]=>Please assign me, Sir/Madam.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
i will  Review Requirements
Understand the functionality of get_land_transaction_history and is_land_approved.
Identify input parameters: land_id.
Determine expected output:
get_land_transaction_history: Array of tuples containing ContractAddress and u64 (timestamp).
is_land_approved: Boolean indicating approval status.

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have a strong backend development background with Cairo. In the past year, I've focused on smart contracts and Web3 technologies, including fingible and non fungible token standards. 

### How I plan on tackling this issue
I would first understand the requirements for the get_land_transaction_history and is_land_approved functions.
For  get_land_transaction_history, I would implement logic to retrieve transaction records for a given land_id, storing them as tuples of (ContractAddress, u64). For is_land_approved, I would create a check to determine if the land meets specific approval criteria. 
Next, I would write unit tests for both functions, covering scenarios like no transactions, multiple transactions, and various approval states, while also managing invalid IDs.

**Comment by SoarinSkySagar** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
GM @fishonamos, I am Sagar Rana, a smart contract developer and full stack engineer. I have 3 years of experience building robust full stack applications and over a year of writing smart contracts. You can see my projects and contributions to some major repos on my GitHub profile. The tech stack I use mainly includes Solidity, Rust, Cairo and Typescript. I am also contributing to the Starknet and Rust ecosystems and building on Cairo and Rust languages. I am interested in contributing to projects like this to learn more about these technologies and help make these projects better. Please assign me as I would be really glad to be a contributor in this project! :)

### How I plan on tackling this issue
I would approach the problem like this:
 - Check out the  `land_registry/src` folder and check all available structs for the available fields
 - Create the function interfaces in `land_registry/src/interface.cairo` like this:
```
#[starknet::interface]
pub trait ILandRegistry<TContractState> {
    fn register_land(
        ref self: TContractState, location: felt252, area: u256, land_use: LandUse,
    ) -> u256;
    fn transfer_land(ref self: TContractState, land_id: u256, new_owner: ContractAddress);
    fn get_land(self: @TContractState, land_id: u256) -> Land;
    fn update_land(ref self: TContractState, land_id: u256, area: u256, land_use: LandUse);
    fn approve_land(ref self: TContractState, land_id: u256);
    fn reject_land(ref self: TContractState, land_id: u256);
    fn is_inspector(self: @TContractState, address: ContractAddress) -> bool;
    fn add_inspector(ref self: TContractState, inspector: ContractAddress);
    fn remove_inspector(ref self: TContractState, inspector: ContractAddress);
     fn get_land_transaction_history(self: @TContractState, land_id: u256) -> Array<(ContractAddress, u64)>;
 fn is_land_approved(self: @TContractState, land_id: u256) -> bool;
}
```
 - Define the functions in `land_registry/src/land_register.cairo`
 - Update the tests to include the new components in `land_registry/tests/test_land_register.cairo`
 - Ensure that all tests are passing and code is neat and clean and then create the PR

## ETA: 2 Days

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To verify the functionality of `get_land_transaction_history` and `is_land_approved`, I will write unit tests for each function. For `get_land_transaction_history`, I will check that it returns the correct transaction history for a given `land_id`, while for `is_land_approved`, I will ensure it accurately indicates the approval status of a specified `land_id`. Additionally, I will test edge cases, such as using a non-existent `land_id`, to confirm proper handling, and ensure all tests pass successfully.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, I'm Eleazar and I'm applying to issue #87.

I estimate this will take 12hours max to complete.


### How I plan on tackling this issue
1. Understand the Purpose of Each Function 
2. Implement the Logic  and Setup assertions for successful execution of the functions
3. Write Unit Tests        
    Test Cases for get_land_transaction_history
    Test Cases for is_land_approved

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo. I am very good at tests.

### How I plan on tackling this issue
To solve this issue in just 3 steps:
1.⁠ ⁠Firstly, Ill make sure get_land_transaction_history and is_land_approved are properly implemented.
2.⁠ ⁠Next, I’ll create test cases covering various scenarios for retrieving transaction history and checking approval status.
3.⁠ ⁠Lastly, I’ll execute the tests to verify that the logic is correct and works as intended

Please assign me, I’m ready to work.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past.

### How I plan on tackling this issue
I will carefully implement the feature requested and write tests to make sure the functionality is working properly with 100% coverage.

ETA 1 day.
