### ISSUE TITLE
 Implement and test set/get land_inspector functions

### ISSUE THREAD

**Issue by fishonamos** [NoshonNetworks/landver#88]
We need to implement, improve, and thoroughly test the functions for setting and getting land inspectors in our LandVer system. This will involve adding new functionality, enhancing existing code, and creating comprehensive tests.

Definition of Done:
• Tests are written to verify the new functionality.

Note: Only applications through the OnlyDust platform will be considered.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.


### How I plan on tackling this issue
i will Validate input parameters.
Check for land existence.
Enforce ownership authorization.

**Comment by Oshioke-Salaki** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a cairo developer with alot of contributions in the starknet ecosystem. I belive i would be a perfect fit for this issue and i would love to show case my skills in this repo if given the chance.

### How I plan on tackling this issue
I would go throught the code base first of all to get a feel of the project and coding style. Then i would start implementing the function. then i would create an event to be fired off when a land inspector is set. Then i would write several test cases for the function to make sure it works as expected and the event is fired off.

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a web3 developer with experience writing smart contracts and testing: Here is my onlydust profile:https://app.onlydust.com/u/No-bodyq

### How I plan on tackling this issue
I will implement the set_land_inspector function using the function parameters and mapping the land_id to the inspector address. I will then write tests to substantiate the new functionality

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a web3 developer with 3 years expeerience writing tests and developing smart contracts

### How I plan on tackling this issue
Properly go through codebase find the invariants , test against it anf figure out specific edge cases to test for  while ensuring it tallies with intended functionality

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To implement and test the set_land_inspector function, I will ensure its correctness and reliability through comprehensive testing. The function will allow assigning an inspector to a specific land ID within the smart contract.

I will begin by defining the set_land_inspector function, which will take land_id of type u256 and inspector of type ContractAddress as parameters. This function will update the contract's state to link the specified inspector with the designated land ID. To maintain security, I will implement access controls to ensure that only authorized users can invoke this function, preventing unauthorized changes to the land inspector assignments.

The core logic will involve updating the contract's state to establish the relationship between the given land ID and the specified inspector address. After completing the implementation, I will write tests to verify the functionality of the set_land_inspector function. These tests will cover successful assignments of a land inspector to valid land IDs, correct state update verification after function calls, and access control checks to ensure unauthorized users cannot execute the function. I will also test edge cases, such as attempts to assign an inspector to a non-existent land ID.

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
Hello, i'm an experienced frontend and block chain developer. I would love to work on this issue.

### How I plan on tackling this issue
- I will understand the function signature
- i will modify the smart contract
- i will Write unit tests to ensure the functions work as expected .
- I will Write integration tests to verify the function works within the overall system.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
I have a solid background in smart contract development and blockchain technology, specifically with platforms like Ethereum and StarkNet. My expertise includes designing and implementing decentralized applications (dApps) with a strong emphasis on security, efficiency, and functionality. I have experience in developing and testing smart contracts that involve complex data management and access control mechanisms. This background equips me to effectively implement and enhance the inspector management functionalities within the LandVer system, ensuring that the new features are robust, secure, and thoroughly tested.

### How I plan on tackling this issue
I would begin by reviewing the existing LandRegistry contract to understand its current structure and functionality related to land management and inspector assignments. I would then implement the set_land_inspector function by adding it to the ILandRegistry trait and defining its logic in the LandRegistry contract, ensuring that only authorized entities can set inspectors through an only_admin access modifier. Proper error handling and event emission would also be incorporated.

Next, I would implement the get_land_inspector function, ensuring it accurately retrieves the inspector's address for a given land ID. I would enhance the inspector management system by adding a function to remove inspectors from specific lands and another to list all lands assigned to a particular inspector. Additionally, I would implement a function to check if an address is an inspector for any land.

To support these features, I would update the Land struct to include an inspector field and establish a mapping to manage inspector assignments efficiently. I would ensure that all functions related to inspector management utilize proper access control through the only_admin modifier.

Finally, I would write comprehensive tests to verify the new functionalities, covering scenarios such as setting and getting inspectors, removing inspectors, and listing lands for a specific inspector. I would also include tests to ensure that only admins can perform restricted actions and to handle error cases appropriately. This structured approach will ensure that the inspector management functionalities are effectively implemented and thoroughly tested, enhancing the integrity of the LandVer system.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/landver).

### My background and how it can be leveraged
i  have experience in cairo and previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contributio

### How I plan on tackling this issue
I will implement a comprehensive land inspector managment sys using a hierarchical validation approach that includes cross-inspector verification nd integrity checks through the Merkle proofs for land assignments. The implementation will feature a dynamic rating system for inspectors based on their verification history, with automated performance metrics influencing their future assignment eligibility.

While this adds significant security features, I believe the centralized inspector assignment model culd be improved by implementing a decentralized consensus mechanism for inspector selection, potentially using a reputation-based staking system.
